### PR TITLE
Refs #16740 - Update all templates to use params macros

### PR DESCRIPTION
**Pull request by ares**
Fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1683350

also is there a reason, why these templates don't live in community templates? This way they would be updated as part of https://github.com/theforeman/community-templates/commit/227ccb5ff717b30a31eb03c752b1d1ad5ed55e6e and we wouldn't have to wait for QE to find it.

### CODE REVIEW

**Comment by ares** [comment]
also note that this is 6.5 only, it won't work with 6.4

**Comment by sideangleside** [comment]
The templates live here just because it was super quick to put them in the RedHatSatellite org many many moons ago when I created this repo. These changes should be merged to the community templates repo. (and this repo retired)

**Comment by ares** [comment]
this should be super trivial, do you plan to open such PR or should I ask someone for help?

**Comment by sideangleside** [comment]
I won't have time in the next week or so to submit a PR.

**Pull request merged**
